name: sinNightMarket
main: org.sinNightMarket.SinNightMarket
version: 1.0.0
api-version: 1.21
depend: [NBTAPI]
commands:
  nightmarket:
    description: Opens NightMarket GUI
    usage: /<command>
    permission: nightmarket.use
permissions:
  nightmarket.use:
    default: true
  nightmarket.admin:
    default: op
